# Generated by Django 4.2.4 on 2023-08-05 07:19

from django.db import migrations, models

def add_initial_data(apps, schema_editor):
    AreaCode = apps.get_model('shelter', 'AreaCode')
    AreaCode.objects.create(code = 1111051500)
    AreaCode.objects.create(code = 1111053000)
    AreaCode.objects.create(code = 1111054000)
    AreaCode.objects.create(code = 1111055000)
    AreaCode.objects.create(code = 1111056000)
    AreaCode.objects.create(code = 1111057000)
    AreaCode.objects.create(code = 1111058000)
    AreaCode.objects.create(code = 1111060000)
    AreaCode.objects.create(code = 1111061500)
    AreaCode.objects.create(code = 1111063000)
    AreaCode.objects.create(code = 1111064000)
    AreaCode.objects.create(code = 1111065000)
    AreaCode.objects.create(code = 1111067000)
    AreaCode.objects.create(code = 1111068000)
    AreaCode.objects.create(code = 1111069000)
    AreaCode.objects.create(code = 1111070000)
    AreaCode.objects.create(code = 1111071000)

class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RunPython(add_initial_data),
    ]